## Import necessary libraries

In [7]:
import numpy as np
from scipy import signal

## Define the state-space matrices

In [14]:
A = np.array([
    [0, 1, 0],
    [0, 0, 4.438],
    [0, -12, -24]
])
b1 = np.array([0, 0, 20]).reshape(-1, 1)
b2 = np.array([0, -7.396, 0]).reshape(-1, 1)
B = np.hstack((b1, b2))
C = np.array([
    [1, 0, 0],
    [0, 1, 0]
])
D = np.array([[0], [0]])

## Create the state-space model using signal.StateSpace

In [15]:
DC_motor = signal.StateSpace(A, b1, C, D)  # Note only first input is used

## Calculate the eigenvalues and right eigenvectors of A

In [16]:
eigenvalues, right_eigenvectors = np.linalg.eig(A)

## Calculate the left eigenvectors of A

In [17]:
_, left_eigenvectors = np.linalg.eig(A.T)

## Display the results

In [18]:
print("Right Eigenvectors (V):")
print(right_eigenvectors)
print("Eigenvalues (Lambda):")
print(eigenvalues)
print("Left Eigenvectors (W):")
print(left_eigenvectors)

Right Eigenvectors (V):
[[ 1.         -0.33290784  0.00938002]
 [ 0.          0.82362581 -0.20191394]
 [ 0.         -0.45914364  0.97935835]]
Eigenvalues (Lambda):
[  0.          -2.47403548 -21.52596452]
Left Eigenvectors (W):
[[ 0.          0.          0.90907852]
 [-0.48691774 -0.97940144  0.40967937]
 [-0.87344783 -0.20192283  0.07575654]]
