## Import necessary libraries

In [1]:
import numpy as np
import control

## Define the first state-space system

In [2]:
A1 = np.array([[0, 1, 0], [0, 0, 1], [-5, -11, -6]])
B1 = np.array([[0], [0], [1]])
C1 = np.array([[1, 0, 1]])
D1 = np.array([[0]])
sys1 = control.ss(A1, B1, C1, D1)
tf1 = control.ss2tf(sys1)

print("Transfer Function (sys1):")
print(tf1)

Transfer Function (sys1):
<TransferFunction>: sys[1]
Inputs (1): ['u[0]']
Outputs (1): ['y[0]']


s^2 - 8.882e-15 s + 1
----------------------
s^3 + 6 s^2 + 11 s + 5



## Define the second state-space system

In [3]:
A2 = np.array([[0, 0, -5], [1, 0, -11], [0, 1, -6]])
B2 = np.array([[1], [0], [1]])
C2 = np.array([[0, 0, 1]])
D2 = np.array([[0]])
sys2 = control.ss(A2, B2, C2, D2)
tf2 = control.ss2tf(sys2)

print("\nTransfer Function (sys2):")
print(tf2)


Transfer Function (sys2):
<TransferFunction>: sys[3]
Inputs (1): ['u[0]']
Outputs (1): ['y[0]']


s^2 - 8.882e-15 s + 1
----------------------
s^3 + 6 s^2 + 11 s + 5



## Define the third state-space system

In [4]:
A3 = np.array([[0, 1, 0], [0, 0, 1], [-5, -11, -6]])
B3 = np.array([[1], [-6], [26]])
C3 = np.array([[1, 0, 0]])
D3 = np.array([[0]])
sys3 = control.ss(A3, B3, C3, D3)
tf3 = control.ss2tf(sys3)

print("\nTransfer Function (sys3):")
print(tf3)


Transfer Function (sys3):
<TransferFunction>: sys[5]
Inputs (1): ['u[0]']
Outputs (1): ['y[0]']


s^2 - 3.375e-14 s + 1
----------------------
s^3 + 6 s^2 + 11 s + 5



## Observability matrix

In [5]:
O3 = control.obsv(A3, C3)
rank_O3 = np.linalg.matrix_rank(O3)
print("\nObservability Matrix (sys3):")
print(O3)
print("Rank of Observability Matrix (sys3):", rank_O3)


Observability Matrix (sys3):
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Rank of Observability Matrix (sys3): 3


## Define the fourth state-space system

In [6]:
A4 = np.array([[0, 0, -5], [1, 0, -11], [0, 1, -6]])
B4 = np.array([[1], [0], [0]])
C4 = np.array([[1, -6, 26]])
D4 = np.array([[0]])
sys4 = control.ss(A4, B4, C4, D4)
tf4 = control.ss2tf(sys4)

print("\nTransfer Function (sys4):")
print(tf4)


Transfer Function (sys4):
<TransferFunction>: sys[7]
Inputs (1): ['u[0]']
Outputs (1): ['y[0]']


s^2 + 5.329e-15 s + 1
----------------------
s^3 + 6 s^2 + 11 s + 5



## Controllability matrix

In [7]:
C4 = control.ctrb(A4, B4)
rank_C4 = np.linalg.matrix_rank(C4)
print("\nControllability Matrix (sys4):")
print(C4)
print("Rank of Controllability Matrix (sys4):", rank_C4)


Controllability Matrix (sys4):
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Rank of Controllability Matrix (sys4): 3


## Transfer function to state-space

In [11]:
num = [1, 0, 1]
den = [1, 6, 11, 5]
sys_tf = control.tf(num, den)
sys5 = control.tf2ss(num, den)
sys_ss = control.ss(sys_tf)

print("\nState-Space Representation from Transfer Function:")
print("A matrix:\n", sys5.A)
print("B matrix:\n", sys5.B)
print("C matrix:\n", sys5.C)
print("D matrix:\n", sys5.D)

print("\nState-Space Representation from Transfer Function:")
print("A matrix:\n", sys_ss.A)
print("B matrix:\n", sys_ss.B)
print("C matrix:\n", sys_ss.C)
print("D matrix:\n", sys_ss.D)


State-Space Representation from Transfer Function:
A matrix:
 [[ -6. -11.  -5.]
 [  1.   0.   0.]
 [  0.   1.   0.]]
B matrix:
 [[1.]
 [0.]
 [0.]]
C matrix:
 [[1. 0. 1.]]
D matrix:
 [[0.]]

State-Space Representation from Transfer Function:
A matrix:
 [[ -6. -11.  -5.]
 [  1.   0.   0.]
 [  0.   1.   0.]]
B matrix:
 [[1.]
 [0.]
 [0.]]
C matrix:
 [[1. 0. 1.]]
D matrix:
 [[0.]]
